name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check for outdated dependencies (optional)
        run: npm outdated || true
      # Uncomment the next step if you have tests
      # - name: Run tests
      #   run: npm test
      - name: Build project
        run: npm run build
      - name: List dist contents for debug
        run: |
          echo "Listing dist directory contents:"
          ls -l dist
          echo "Listing dist/assets directory contents:"
          ls -l dist/assets || echo "No assets directory"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Show deployed URL
        run: |
          echo "Your site is live at: https://rajamuhammadawais.github.io/RajaAwais/"
